In [1]:
%pip install -r requirements.txt

Requirement already satisfied: pint>=0.18 in /opt/conda/lib/python3.9/site-packages (from -r requirements.txt (line 3)) (0.20.1)
Requirement already satisfied: requests>=2.26.0 in /opt/conda/lib/python3.9/site-packages (from -r requirements.txt (line 6)) (2.26.0)
Requirement already satisfied: python-gnupg in /opt/conda/lib/python3.9/site-packages (from -r requirements.txt (line 8)) (0.5.0)
Requirement already satisfied: eep153_tools in /opt/conda/lib/python3.9/site-packages (from -r requirements.txt (line 10)) (0.11)
Requirement already satisfied: fooddatacentral in /opt/conda/lib/python3.9/site-packages (from -r requirements.txt (line 12)) (1.0.9)
Requirement already satisfied: charset-normalizer~=2.0.0 in /opt/conda/lib/python3.9/site-packages (from requests>=2.26.0->-r requirements.txt (line 6)) (2.0.0)
Requirement already satisfied: certifi>=2017.4.17 in /opt/conda/lib/python3.9/site-packages (from requests>=2.26.0->-r requirements.txt (line 6)) (2021.10.8)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /opt/conda/lib/python3.9/site-packages (from requests>=2.26.0->-r requirements.txt (line 6)) (1.26.7)
Requirement already satisfied: idna<4,>=2.5 in /opt/conda/lib/python3.9/site-packages (from requests>=2.26.0->-r requirements.txt (line 6)) (3.1)
Note: you may need to restart the kernel to use updated packages.

In [2]:
import fooddatacentral as fdc

In [3]:
import pandas as pd
from eep153_tools.sheets import read_sheets

In [10]:
RDIs = read_sheets('https://docs.google.com/spreadsheets/d/1y95IsQ4HKspPW3HHDtH7QMtlDA66IUsCHJLutVL-MMc/')

bmin = RDIs['diet_minimums'].set_index('Nutrition')

# Drop string describing source
bmin = bmin.drop('Source',axis=1)
bmin

Key available for students@eep153.iam.gserviceaccount.com.

,C 1-3,F 4-8,M 4-8,F 9-13,M 9-13,F 14-18,M 14-18,F 19-30,M 19-30,F 31-50,M 31-50,F 51+,M 51+
Nutrition,,,,,,,,,,,,,
Energy,1000.0,1200.0,1400.0,1600.0,1800.0,1800.0,2200.0,2000.0,2400.0,1800.0,2200.0,1600.0,2000.0
Protein,13.0,19.0,19.0,34.0,34.0,46.0,52.0,46.0,56.0,46.0,56.0,46.0,56.0
"Fiber, total dietary",14.0,16.8,19.6,22.4,25.2,25.2,30.8,28.0,33.6,25.2,30.8,22.4,28.0
"Folate, DFE",150.0,200.0,200.0,300.0,300.0,400.0,400.0,400.0,400.0,400.0,400.0,400.0,400.0
"Calcium, Ca",700.0,1000.0,1000.0,1300.0,1300.0,1300.0,1300.0,1000.0,1000.0,1000.0,1000.0,1200.0,1000.0
"Carbohydrate, by difference",130.0,130.0,130.0,130.0,130.0,130.0,130.0,130.0,130.0,130.0,130.0,130.0,130.0
"Iron, Fe",7.0,10.0,10.0,8.0,8.0,15.0,11.0,18.0,8.0,18.0,8.0,8.0,8.0
"Magnesium, Mg",80.0,130.0,130.0,240.0,240.0,360.0,410.0,310.0,400.0,320.0,420.0,320.0,420.0
Niacin,6.0,8.0,8.0,12.0,12.0,14.0,16.0,14.0,16.0,14.0,16.0,14.0,16.0
"Phosphorus, P",460.0,500.0,500.0,1250.0,1250.0,1250.0,1250.0,700.0,700.0,700.0,700.0,700.0,700.0
"Potassium, K",3000.0,3800.0,3800.0,4500.0,4500.0,4700.0,4700.0,4700.0,4700.0,4700.0,4700.0,4700.0,4700.0
Riboflavin,0.5,0.6,0.6,0.9,0.9,1.0,1.3,1.1,1.3,1.1,1.3,1.1,1.3
Thiamin,0.5,0.6,0.6,0.9,0.9,1.0,1.2,1.1,1.2,1.1,1.2,1.1,1.2
"Vitamin A, RAE",300.0,400.0,400.0,600.0,600.0,700.0,900.0,700.0,900.0,700.0,900.0,700.0,900.0
Vitamin B-12,0.9,1.2,1.2,1.8,1.8,2.4,2.4,2.4,2.4,2.4,2.4,2.4,2.4
Vitamin B-6,0.5,0.6,0.6,1.0,1.0,1.2,1.3,1.3,1.3,1.3,1.3,1.5,1.7
"Vitamin C, total ascorbic acid",15.0,25.0,25.0,45.0,45.0,65.0,75.0,75.0,90.0,75.0,90.0,75.0,90.0
Vitamin E (alpha-tocopherol),6.0,7.0,7.0,11.0,11.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0
Vitamin K (phylloquinone),30.0,55.0,55.0,60.0,60.0,75.0,75.0,90.0,120.0,90.0,120.0,90.0,120.0
"Zinc, Zn",3.0,5.0,5.0,8.0,8.0,9.0,11.0,8.0,11.0,8.0,11.0,8.0,11.0

In [21]:
#This is our RDI Finder Function
# inputs: age as a integer, sex as "F" for female or "M" for male 

def rdi_finder(age, sex): 
    if age < 4: 
        bmin.iloc[:, 0]
    if sex == "F": 
        if age >= 4 and age <= 8:
            return bmin.iloc[:, 1]
        if age >= 9 and age <= 13:
            return bmin.iloc[:, 3]
        if age >= 14 and age <= 18: 
            return bmin.iloc[:, 5]
        if age >= 19 and age <= 30: 
            return bmin.iloc[:, 7]
        if age >= 31 and age <= 50: 
            return bmin.iloc[:, 9]
        else: 
            return bmin.iloc[:,11]
    else: 
        if age >= 4 and age <= 8:
            return bmin.iloc[:, 2]
        if age >= 9 and age <= 13:
            return bmin.iloc[:, 4]
        if age >= 14 and age <= 18: 
            return bmin.iloc[:, 6]
        if age >= 19 and age <= 30: 
            return bmin.iloc[:, 8]
        if age >= 31 and age <= 50: 
            return bmin.iloc[:, 10]
        else: 
            return bmin.iloc[:,12]
normal_male_21 = rdi_finder(21, "M")

In [75]:
df_comparison = pd.DataFrame(normal_male_21)
df_comparison.rename(columns = {"M 19-30": "Male Student"}, inplace = True)
# Adding football athlete requirements 
football = [4000, 192, 35, 400, 1300, 680, 15, 400, 20, 1250, 4700, 1.7, 1.2, 1200, 2.5, 1.6, 200, 15, 120, 15]
df_comparison["Football Athlete"] = football
df_comparison

                                Male Student  Football Athlete
Nutrition
Energy                                2400.0            4000.0
Protein                                 56.0             192.0
Fiber, total dietary                    33.6              35.0
Folate, DFE                            400.0             400.0
Calcium, Ca                           1000.0            1300.0
Carbohydrate, by difference            130.0             680.0
Iron, Fe                                 8.0              15.0
Magnesium, Mg                          400.0             400.0
Niacin                                  16.0              20.0
Phosphorus, P                          700.0            1250.0
Potassium, K                          4700.0            4700.0
Riboflavin                               1.3               1.7
Thiamin                                  1.2               1.2
Vitamin A, RAE                         900.0            1200.0
Vitamin B-12                             2.4               2.5
Vitamin B-6                              1.3               1.6
Vitamin C, total ascorbic acid          90.0             200.0
Vitamin E (alpha-tocopherol)            15.0              15.0
Vitamin K (phylloquinone)              120.0             120.0
Zinc, Zn                                11.0              15.0

In [80]:
bmax_normal = RDIs['diet_maximums'].set_index('Nutrition')

# Drop string describing source
bmax = bmax_normal.drop('Source',axis=1)
bmax = pd.DataFrame(bmax_normal.iloc[:,9])
bmax.rename(columns = {"M 19-30": "Male Student"}, inplace = True)
bmax["Football Athlete"] = [5000, 9000]
bmax

            Male Student  Football Athlete
Nutrition
Sodium, Na          2300              5000
Energy              3100              9000

In [88]:
#Our Grocery List 
df_grocery = read_sheets("https://docs.google.com/spreadsheets/d/1IAsnG9HXwOc3vbsPXCbWgJp1WFO3Zn72p0e1l6t8BCc/edit#gid=1147509308")

df_grocery = df_grocery.set_index('Food')

df_grocery

Key available for students@eep153.iam.gserviceaccount.com.

AttributeError: 'dict' object has no attribute 'set_index'